"""Professional portfolio analytics workbook for Finance Utility Suite."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Final

import pandas as pd
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.chart.label import DataLabelList
from openpyxl.formatting.rule import ColorScaleRule, CellIsRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo

from desktop.reports.analytics_engine import AnalyticsSummary, PortfolioAnalyticsEngine
from desktop.reports.base_dashboard_report import BaseDashboardReport
from desktop.reports.performance_engine import PerformanceDataError, PerformanceEngine, PerformanceSummary


class AnalyticsReport(BaseDashboardReport):
    """Create a multi-sheet executive portfolio analytics workbook.

    ``history_dataframe`` is optional and should contain Date and Portfolio Value
    (or supported aliases). When omitted, the workbook remains fully usable and
    clearly marks historical analytics as unavailable.
    """

    VERSION: Final[str] = "1.38.1"
    BLUE = "17365D"; MID = "2F75B5"; LIGHT = "D9EAF7"; WHITE = "FFFFFF"
    GREEN = "008000"; PALE_GREEN = "E2F0D9"; RED = "C00000"; PALE_RED = "FCE4D6"
    GOLD = "FFC000"; GREY = "E7E6E6"; DARK_GREY = "666666"
    CURRENCY = '₹#,##0.00;[Red]-₹#,##0.00'; PERCENT = '0.00"%";[Red]-0.00"%"'
    THIN_GREY = Side(style="thin", color="D9E1F2")

    def __init__(
        self,
        dataframe: pd.DataFrame,
        summary_data: dict[str, Any] | None = None,
        *,
        portfolio_name: str = "Portfolio",
        history_dataframe: pd.DataFrame | None = None,
    ) -> None:
        self.source_dataframe = dataframe.copy() if dataframe is not None else pd.DataFrame()
        self.history_dataframe = history_dataframe.copy() if history_dataframe is not None else None
        self.summary_overrides = dict(summary_data or {})
        self.portfolio_name = str(portfolio_name).strip() or "Portfolio"
        self.engine = PortfolioAnalyticsEngine()
        self.performance_engine = PerformanceEngine()
        self.dataframe = pd.DataFrame()
        self.summary: AnalyticsSummary | None = None
        self.performance_summary: PerformanceSummary | None = None
        self.sector_data = pd.DataFrame()
        self.contribution_data = pd.DataFrame()
        self.monthly_data = pd.DataFrame()
        self.yearly_data = pd.DataFrame()
        self.growth_data = pd.DataFrame()
        self.cagr_value: float | None = None
        super().__init__(
            report_title=f"{self.portfolio_name} Analytics Report",
            report_subject="Portfolio performance, attribution and executive analytics",
            report_description="Professional analytics workbook generated by Finance Utility Suite.",
            report_keywords="analytics, portfolio, performance, attribution, sector, monthly returns",
        )

    def build(self, writer: pd.ExcelWriter, export_time: datetime) -> None:
        self.dataframe = self.engine.prepare(self.source_dataframe)
        self.summary = self.engine.summarize(self.source_dataframe)
        self.performance_summary = self.performance_engine.calculate_summary(self.source_dataframe)
        self.sector_data = self.performance_engine.sector_performance(self.source_dataframe)
        self.contribution_data = self.performance_engine.holding_contribution(self.source_dataframe)
        self._prepare_history_data()

        self._dashboard(writer, export_time)
        self._performance_sheet(writer)
        self._monthly_returns_sheet(writer)
        self._sector_analysis_sheet(writer)
        self._top_performers_sheet(writer)
        self._summary_sheet(writer)
        self._chart_data(writer)
        self._charts(writer.book)
        writer.book["Chart Data"].sheet_state = "hidden"

    def finalize(self, writer: pd.ExcelWriter) -> None:
        writer.book.active = writer.book.sheetnames.index("Dashboard")

    def _prepare_history_data(self) -> None:
        if self.history_dataframe is None or self.history_dataframe.empty:
            return
        try:
            self.growth_data = self.performance_engine.portfolio_growth(self.history_dataframe)
            self.monthly_data = self.performance_engine.monthly_returns(self.history_dataframe)
            self.yearly_data = self.performance_engine.yearly_returns(self.history_dataframe)
            if len(self.growth_data) >= 2:
                self.cagr_value = self.performance_engine.cagr(self.history_dataframe)
        except PerformanceDataError:
            # Holdings analytics should still export when optional history is invalid.
            self.growth_data = pd.DataFrame()
            self.monthly_data = pd.DataFrame()
            self.yearly_data = pd.DataFrame()
            self.cagr_value = None

    def _title(self, ws, title: str, subtitle: str, end_column: int) -> None:
        ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=end_column)
        ws.cell(1, 1, title)
        ws.cell(1, 1).font = Font(name="Segoe UI", size=18, bold=True, color=self.WHITE)
        ws.cell(1, 1).fill = PatternFill("solid", fgColor=self.BLUE)
        ws.cell(1, 1).alignment = Alignment(horizontal="center", vertical="center")
        ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=end_column)
        ws.cell(2, 1, subtitle)
        ws.cell(2, 1).font = Font(name="Segoe UI", italic=True, color=self.DARK_GREY)
        ws.cell(2, 1).alignment = Alignment(horizontal="center")
        ws.row_dimensions[1].height = 30

    def _section(self, ws, row: int, title: str, end_column: int) -> None:
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=end_column)
        cell = ws.cell(row, 1, title)
        cell.fill = PatternFill("solid", fgColor=self.BLUE)
        cell.font = Font(name="Segoe UI", bold=True, color=self.WHITE)
        cell.alignment = Alignment(horizontal="left")

    def _style_table(self, ws, start_row: int, end_row: int, end_col: int, name: str) -> None:
        if end_row <= start_row:
            return
        for cell in ws[start_row]:
            if cell.column <= end_col:
                cell.fill = PatternFill("solid", fgColor=self.MID)
                cell.font = Font(name="Segoe UI", bold=True, color=self.WHITE)
                cell.alignment = Alignment(horizontal="center")
        ref = f"A{start_row}:{get_column_letter(end_col)}{end_row}"
        table = Table(displayName=name, ref=ref)
        table.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True, showFirstColumn=False, showLastColumn=False)
        ws.add_table(table)

    def _dashboard(self, writer: pd.ExcelWriter, export_time: datetime) -> None:
        ws = writer.book.create_sheet("Dashboard")
        self._title(ws, f"{self.portfolio_name} Analytics Dashboard", f"Generated: {export_time:%d-%b-%Y %I:%M %p}", 10)
        s = self.summary; p = self.performance_summary
        assert s is not None and p is not None
        metrics = [
            ("Total Investment", s.total_investment, self.CURRENCY), ("Current Value", s.current_value, self.CURRENCY),
            ("Profit / Loss", s.profit_loss, self.CURRENCY), ("Overall Return", s.return_pct, self.PERCENT),
            ("Holdings", s.holdings_count, "0"), ("Sectors", s.sector_count, "0"),
            ("Largest Holding", s.largest_holding_pct, self.PERCENT), ("Health Score", s.portfolio_health_score, '0.0" / 100"'),
        ]
        positions = [(4,1),(4,3),(4,5),(4,7),(8,1),(8,3),(8,5),(8,7)]
        for (label, value, fmt), (row, col) in zip(metrics, positions):
            ws.merge_cells(start_row=row, start_column=col, end_row=row, end_column=col+1)
            ws.merge_cells(start_row=row+1, start_column=col, end_row=row+2, end_column=col+1)
            label_cell = ws.cell(row, col, label); value_cell = ws.cell(row+1, col, value)
            label_cell.fill = PatternFill("solid", fgColor=self.MID); label_cell.font = Font(name="Segoe UI", bold=True, color=self.WHITE)
            label_cell.alignment = Alignment(horizontal="center", vertical="center")
            value_cell.fill = PatternFill("solid", fgColor=self.LIGHT); value_cell.font = Font(name="Segoe UI", size=14, bold=True)
            value_cell.alignment = Alignment(horizontal="center", vertical="center"); value_cell.number_format = fmt
            for r in range(row, row+3):
                for c in range(col, col+2): ws.cell(r,c).border = Border(left=self.THIN_GREY,right=self.THIN_GREY,top=self.THIN_GREY,bottom=self.THIN_GREY)

        self._section(ws, 12, "Executive Performance Snapshot", 10)
        snapshot = [
            ("Best Performer", p.best_stock, p.best_stock_return_pct),
            ("Worst Performer", p.worst_stock, p.worst_stock_return_pct),
            ("Best Sector", p.best_sector, p.best_sector_return_pct),
            ("Worst Sector", p.worst_sector, p.worst_sector_return_pct),
            ("Profitable / Losing", f"{p.winners} / {p.losers}", None),
            ("Historical CAGR", "Not supplied" if self.cagr_value is None else "Available", self.cagr_value),
        ]
        for i, (label, value, pct) in enumerate(snapshot):
            row = 13 + i
            ws.cell(row,1,label).font = Font(name="Segoe UI", bold=True)
            ws.cell(row,2,value)
            if pct is not None:
                ws.cell(row,3,pct); ws.cell(row,3).number_format = self.PERCENT
                ws.cell(row,3).font = Font(color=self.GREEN if pct >= 0 else self.RED, bold=True)

        for col in range(1,11): ws.column_dimensions[get_column_letter(col)].width = 15
        ws.column_dimensions["A"].width = 21; ws.column_dimensions["B"].width = 18
        self.configure_worksheet(ws, freeze_panes="A3", print_area="A1:J40")

    def _performance_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Performance Summary")
        self._title(ws, "Performance Summary", "Portfolio-level return and attribution overview", 8)
        s = self.summary; p = self.performance_summary
        assert s is not None and p is not None
        rows = [
            ("Invested Value", s.total_investment, self.CURRENCY), ("Current Value", s.current_value, self.CURRENCY),
            ("Profit / Loss", s.profit_loss, self.CURRENCY), ("Overall Return", s.return_pct, self.PERCENT),
            ("CAGR", self.cagr_value if self.cagr_value is not None else "History not supplied", self.PERCENT),
            ("Winners", p.winners, "0"), ("Losers", p.losers, "0"), ("Breakeven", p.breakeven, "0"),
            ("Best Stock", p.best_stock, "General"), ("Best Stock Return", p.best_stock_return_pct, self.PERCENT),
            ("Worst Stock", p.worst_stock, "General"), ("Worst Stock Return", p.worst_stock_return_pct, self.PERCENT),
            ("Best Sector", p.best_sector, "General"), ("Best Sector Return", p.best_sector_return_pct, self.PERCENT),
            ("Worst Sector", p.worst_sector, "General"), ("Worst Sector Return", p.worst_sector_return_pct, self.PERCENT),
        ]
        ws.append([]); ws.append(["Metric", "Value"])
        start = 4
        for label, value, fmt in rows:
            ws.append([label, value]); ws.cell(ws.max_row,2).number_format = fmt
        self._style_table(ws, start, ws.max_row, 2, "PerformanceSummaryTable")
        ws.column_dimensions["A"].width = 28; ws.column_dimensions["B"].width = 24
        ws.conditional_formatting.add(f"B{start+1}:B{ws.max_row}", CellIsRule(operator="lessThan", formula=["0"], font=Font(color=self.RED)))
        self.configure_worksheet(ws, freeze_panes="A5", print_area=f"A1:H{ws.max_row+2}")

    def _monthly_returns_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Monthly Returns")
        self._title(ws, "Monthly & Yearly Returns", "Historical portfolio performance; optional history input", 8)
        if self.monthly_data.empty:
            ws.merge_cells("A4:H6"); ws["A4"] = "Historical portfolio data was not supplied. Pass history_dataframe with Date and Portfolio Value to populate this sheet and growth charts."
            ws["A4"].alignment = Alignment(wrap_text=True, horizontal="center", vertical="center")
            ws["A4"].fill = PatternFill("solid", fgColor=self.LIGHT)
            for c in range(1,9): ws.column_dimensions[get_column_letter(c)].width = 16
            self.configure_worksheet(ws, print_area="A1:H10")
            return
        ws.append([]); ws.append(["Period", "Period End", "Portfolio Value", "Return %"])
        start = 4
        for _, row in self.monthly_data.iterrows():
            ws.append([row["Period"], row["Date"].to_pydatetime(), float(row["Portfolio Value"]), float(row["Return %"])])
        self._style_table(ws, start, ws.max_row, 4, "MonthlyReturnsTable")
        for row in range(start+1, ws.max_row+1):
            ws.cell(row,2).number_format = "dd-mmm-yyyy"; ws.cell(row,3).number_format = self.CURRENCY; ws.cell(row,4).number_format = self.PERCENT
        ws.conditional_formatting.add(f"D{start+1}:D{ws.max_row}", ColorScaleRule(start_type="min", start_color="F8696B", mid_type="percentile", mid_value=50, mid_color="FFEB84", end_type="max", end_color="63BE7B"))
        year_col = 6
        ws.cell(start,year_col,"Year"); ws.cell(start,year_col+1,"Portfolio Value"); ws.cell(start,year_col+2,"Return %")
        for cell in ws[start][year_col-1:year_col+2]: cell.fill=PatternFill("solid",fgColor=self.MID); cell.font=Font(bold=True,color=self.WHITE)
        for _, row in self.yearly_data.iterrows(): ws.append([]) if False else None
        for offset,(_,row) in enumerate(self.yearly_data.iterrows(), start=start+1):
            ws.cell(offset,year_col,int(row["Year"])); ws.cell(offset,year_col+1,float(row["Portfolio Value"])); ws.cell(offset,year_col+2,float(row["Return %"]))
            ws.cell(offset,year_col+1).number_format=self.CURRENCY; ws.cell(offset,year_col+2).number_format=self.PERCENT
        for c,w in {"A":12,"B":16,"C":18,"D":14,"F":12,"G":18,"H":14}.items(): ws.column_dimensions[c].width=w
        self.configure_worksheet(ws, freeze_panes="A5", print_area=f"A1:H{max(ws.max_row+2,20)}")

    def _sector_analysis_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Sector Analysis")
        self._title(ws, "Sector Analysis", "Allocation, performance and contribution by sector", 8)
        headers = list(self.sector_data.columns)
        ws.append([]); ws.append(headers); start=4
        for _, row in self.sector_data.iterrows(): ws.append([row[h] for h in headers])
        self._style_table(ws,start,ws.max_row,len(headers),"SectorAnalysisTable")
        for r in range(start+1,ws.max_row+1):
            for c in (3,4,5): ws.cell(r,c).number_format=self.CURRENCY
            for c in (6,7,8): ws.cell(r,c).number_format=self.PERCENT
        for c in (6,8): ws.conditional_formatting.add(f"{get_column_letter(c)}{start+1}:{get_column_letter(c)}{ws.max_row}", ColorScaleRule(start_type="min",start_color="F8696B",mid_type="percentile",mid_value=50,mid_color="FFEB84",end_type="max",end_color="63BE7B"))
        for idx,h in enumerate(headers,1): ws.column_dimensions[get_column_letter(idx)].width=max(13,min(22,len(h)+5))
        self.configure_worksheet(ws,freeze_panes="A5",print_area=f"A1:H{ws.max_row+16}")

    def _top_performers_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Top Performers")
        self._title(ws, "Top Performers & Attribution", "Winning, losing and contribution rankings", 12)
        gainers=self.performance_engine.top_gainers(self.source_dataframe,10)
        losers=self.performance_engine.top_losers(self.source_dataframe,10)
        cols=["Symbol","Sector","Investment","Current Value","Profit","Return %","Contribution %"]
        ws["A4"]="Top Winners"; ws["A4"].font=Font(bold=True,color=self.WHITE); ws["A4"].fill=PatternFill("solid",fgColor=self.GREEN)
        ws["I4"]="Top Losers"; ws["I4"].font=Font(bold=True,color=self.WHITE); ws["I4"].fill=PatternFill("solid",fgColor=self.RED)
        for i,h in enumerate(cols,1): ws.cell(5,i,h); ws.cell(5,i+8,h)
        for i,(_,row) in enumerate(gainers.iterrows(),6):
            for j,h in enumerate(cols,1): ws.cell(i,j,row[h])
        for i,(_,row) in enumerate(losers.iterrows(),6):
            for j,h in enumerate(cols,9): ws.cell(i,j,row[cols[j-9]])
        end=max(5+len(gainers),5+len(losers))
        for c in list(range(1,8))+list(range(9,16)):
            ws.cell(5,c).fill=PatternFill("solid",fgColor=self.MID); ws.cell(5,c).font=Font(bold=True,color=self.WHITE)
        for r in range(6,end+1):
            for c in (3,4,5,11,12,13): ws.cell(r,c).number_format=self.CURRENCY
            for c in (6,7,14,15): ws.cell(r,c).number_format=self.PERCENT
        if len(gainers): self._style_table(ws,5,5+len(gainers),7,"TopWinnersTable")
        if len(losers):
            ref=f"I5:O{5+len(losers)}"; t=Table(displayName="TopLosersTable",ref=ref); t.tableStyleInfo=TableStyleInfo(name="TableStyleMedium3",showRowStripes=True); ws.add_table(t)
        for c in range(1,16): ws.column_dimensions[get_column_letter(c)].width=15
        ws.column_dimensions["A"].width=13; ws.column_dimensions["B"].width=18; ws.column_dimensions["I"].width=13; ws.column_dimensions["J"].width=18
        self.configure_worksheet(ws,freeze_panes="A6",print_area=f"A1:O{end+2}")

    def _summary_sheet(self, writer: pd.ExcelWriter) -> None:
        ws=writer.book.create_sheet("Summary")
        self._title(ws,"Analytics Metrics","Machine-readable KPI summary",4)
        s=self.summary; p=self.performance_summary; assert s is not None and p is not None
        rows=[("Total Investment",s.total_investment),("Current Value",s.current_value),("Profit / Loss",s.profit_loss),("Return %",s.return_pct),("Holdings Count",s.holdings_count),("Sector Count",s.sector_count),("Largest Holding Symbol",s.largest_holding_symbol),("Largest Holding Value",s.largest_holding_value),("Largest Holding %",s.largest_holding_pct),("Average Position Value",s.average_position_value),("Profitable Holdings",s.profitable_holdings),("Loss-making Holdings",s.loss_making_holdings),("Portfolio Health Score",s.portfolio_health_score),("Best Performer",p.best_stock),("Best Performer Return %",p.best_stock_return_pct),("Worst Performer",p.worst_stock),("Worst Performer Return %",p.worst_stock_return_pct),("Best Sector",p.best_sector),("Best Sector Return %",p.best_sector_return_pct),("Worst Sector",p.worst_sector),("Worst Sector Return %",p.worst_sector_return_pct),("CAGR",self.cagr_value if self.cagr_value is not None else "History not supplied")]
        ws.append([]); ws.append(["Metric","Value"]); start=4
        for row in rows: ws.append(row)
        self._style_table(ws,start,ws.max_row,2,"AnalyticsMetricsTable")
        currency_labels={"Total Investment","Current Value","Profit / Loss","Largest Holding Value","Average Position Value"}
        percent_labels={"Return %","Largest Holding %","Best Performer Return %","Worst Performer Return %","Best Sector Return %","Worst Sector Return %","CAGR"}
        for r in range(start+1,ws.max_row+1):
            label=ws.cell(r,1).value
            if label in currency_labels: ws.cell(r,2).number_format=self.CURRENCY
            elif label in percent_labels and isinstance(ws.cell(r,2).value,(int,float)): ws.cell(r,2).number_format=self.PERCENT
        ws.column_dimensions["A"].width=30; ws.column_dimensions["B"].width=24
        self.configure_worksheet(ws,freeze_panes="A5",print_area=f"A1:B{ws.max_row}")

    def _chart_data(self, writer: pd.ExcelWriter) -> None:
        ws=writer.book.create_sheet("Chart Data")
        ws.append(["Symbol","Current Value","Profit","Allocation %","Sector","Return %"])
        for _,row in self.dataframe.iterrows(): ws.append([row["Symbol"],float(row["Current Value"]),float(row["Profit"]),float(row["Allocation %"]),row["Sector"],float(row["Return %"])])
        ws["H1"]="Sector"; ws["I1"]="Current Value"; ws["J1"]="Profit"; ws["K1"]="Return %"
        for off,(_,row) in enumerate(self.sector_data.iterrows(),2):
            ws.cell(off,8,row["Sector"]); ws.cell(off,9,float(row["Current Value"])); ws.cell(off,10,float(row["Profit"])); ws.cell(off,11,float(row["Return %"]))
        ws["M1"]="Period"; ws["N1"]="Portfolio Value"; ws["O1"]="Return %"
        for off,(_,row) in enumerate(self.monthly_data.iterrows(),2):
            ws.cell(off,13,row["Period"]); ws.cell(off,14,float(row["Portfolio Value"])); ws.cell(off,15,float(row["Return %"]))
        ws["Q1"]="Date"; ws["R1"]="Portfolio Value"; ws["S1"]="Cumulative Return %"
        for off,(_,row) in enumerate(self.growth_data.iterrows(),2):
            ws.cell(off,17,row["Date"].to_pydatetime()); ws.cell(off,18,float(row["Portfolio Value"])); ws.cell(off,19,float(row["Cumulative Return %"]))

    def _charts(self, workbook) -> None:
        dashboard=workbook["Dashboard"]; data=workbook["Chart Data"]
        holdings_rows=min(len(self.dataframe),10)+1
        bar=BarChart(); bar.type="bar"; bar.style=10; bar.title="Top Holdings by Current Value"; bar.x_axis.title="Current Value"; bar.height=7; bar.width=13
        bar.add_data(Reference(data,min_col=2,min_row=1,max_row=holdings_rows),titles_from_data=True); bar.set_categories(Reference(data,min_col=1,min_row=2,max_row=holdings_rows)); dashboard.add_chart(bar,"A20")
        sector_rows=len(self.sector_data)+1
        pie=PieChart(); pie.title="Sector Allocation"; pie.height=7; pie.width=11
        pie.add_data(Reference(data,min_col=9,min_row=1,max_row=sector_rows),titles_from_data=True); pie.set_categories(Reference(data,min_col=8,min_row=2,max_row=sector_rows)); pie.dataLabels=DataLabelList(); pie.dataLabels.showPercent=True; dashboard.add_chart(pie,"F20")
        if not self.monthly_data.empty:
            ws=workbook["Monthly Returns"]
            rows=len(self.monthly_data)+1
            monthly=BarChart(); monthly.type="col"; monthly.style=10; monthly.title="Monthly Returns"; monthly.y_axis.title="Return %"; monthly.height=7; monthly.width=13
            monthly.add_data(Reference(data,min_col=15,min_row=1,max_row=rows),titles_from_data=True); monthly.set_categories(Reference(data,min_col=13,min_row=2,max_row=rows)); ws.add_chart(monthly,"A12")
        if not self.growth_data.empty:
            ws=workbook["Performance Summary"]
            rows=len(self.growth_data)+1
            line=LineChart(); line.style=13; line.title="Portfolio Growth"; line.y_axis.title="Portfolio Value"; line.height=8; line.width=15
            line.add_data(Reference(data,min_col=18,min_row=1,max_row=rows),titles_from_data=True); line.set_categories(Reference(data,min_col=17,min_row=2,max_row=rows)); ws.add_chart(line,"D4")
        sector_ws=workbook["Sector Analysis"]
        return_bar=BarChart(); return_bar.type="col"; return_bar.style=10; return_bar.title="Sector Return %"; return_bar.y_axis.title="Return %"; return_bar.height=7; return_bar.width=13
        return_bar.add_data(Reference(data,min_col=11,min_row=1,max_row=sector_rows),titles_from_data=True); return_bar.set_categories(Reference(data,min_col=8,min_row=2,max_row=sector_rows)); sector_ws.add_chart(return_bar,"A12")
