"""Analytics Excel report - Phase 1 executive dashboard and core KPIs."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Final

import pandas as pd
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.chart.label import DataLabelList
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo

from desktop.reports.analytics_engine import AnalyticsSummary, PortfolioAnalyticsEngine
from desktop.reports.base_dashboard_report import BaseDashboardReport


class AnalyticsReport(BaseDashboardReport):
    VERSION: Final[str] = "1.38.0"
    BLUE = "17365D"; MID = "2F75B5"; LIGHT = "D9EAF7"; WHITE = "FFFFFF"
    GREEN = "008000"; RED = "C00000"; GOLD = "FFC000"; GREY = "E7E6E6"
    CURRENCY = '₹#,##0.00;[Red]-₹#,##0.00'; PERCENT = '0.00"%"'

    def __init__(self, dataframe: pd.DataFrame, summary_data: dict[str, Any] | None = None, *, portfolio_name: str = "Portfolio") -> None:
        self.source_dataframe = dataframe.copy() if dataframe is not None else pd.DataFrame()
        self.summary_overrides = dict(summary_data or {})
        self.portfolio_name = str(portfolio_name).strip() or "Portfolio"
        self.engine = PortfolioAnalyticsEngine()
        self.dataframe = pd.DataFrame()
        self.summary: AnalyticsSummary | None = None
        super().__init__(
            report_title=f"{self.portfolio_name} Analytics Report",
            report_subject="Portfolio executive analytics and KPI summary",
            report_description="Analytics report generated by Finance Utility Suite.",
            report_keywords="analytics, portfolio, KPI, allocation, performance, health score",
        )

    def build(self, writer: pd.ExcelWriter, export_time: datetime) -> None:
        self.dataframe = self.engine.prepare(self.source_dataframe)
        self.summary = self.engine.summarize(self.source_dataframe)
        self._dashboard(writer, export_time)
        self._summary_sheet(writer)
        self._chart_data(writer)
        self._charts(writer.book)
        writer.book["Chart Data"].sheet_state = "hidden"

    def finalize(self, writer: pd.ExcelWriter) -> None:
        """Select Dashboard after the report-engine placeholder is removed."""
        writer.book.active = writer.book.sheetnames.index("Dashboard")

    def _dashboard(self, writer: pd.ExcelWriter, export_time: datetime) -> None:
        ws = writer.book.create_sheet("Dashboard")
        ws.merge_cells("A1:H1"); ws["A1"] = f"{self.portfolio_name} Analytics Dashboard"
        ws["A1"].font = Font(name="Segoe UI", size=20, bold=True, color=self.WHITE)
        ws["A1"].fill = PatternFill("solid", fgColor=self.BLUE); ws["A1"].alignment = Alignment(horizontal="center")
        ws.merge_cells("A2:H2"); ws["A2"] = f"Generated: {export_time:%d-%b-%Y %I:%M %p}"
        ws["A2"].alignment = Alignment(horizontal="center"); ws["A2"].font = Font(name="Segoe UI", italic=True, color="666666")
        s = self.summary
        assert s is not None
        metrics = [
            ("Total Investment", s.total_investment, self.CURRENCY), ("Current Value", s.current_value, self.CURRENCY),
            ("Profit / Loss", s.profit_loss, self.CURRENCY), ("Overall Return", s.return_pct, self.PERCENT),
            ("Holdings", s.holdings_count, "0"), ("Sectors", s.sector_count, "0"),
            ("Largest Holding", s.largest_holding_pct, self.PERCENT), ("Health Score", s.portfolio_health_score, '0.0" / 100"'),
        ]
        positions = [(4,1),(4,3),(4,5),(4,7),(8,1),(8,3),(8,5),(8,7)]
        for (label, value, fmt), (row, col) in zip(metrics, positions):
            ws.merge_cells(start_row=row, start_column=col, end_row=row, end_column=col+1)
            ws.merge_cells(start_row=row+1, start_column=col, end_row=row+2, end_column=col+1)
            label_cell=ws.cell(row,col,label); value_cell=ws.cell(row+1,col,value)
            label_cell.fill=PatternFill("solid", fgColor=self.MID); label_cell.font=Font(name="Segoe UI", bold=True, color=self.WHITE)
            label_cell.alignment=Alignment(horizontal="center", vertical="center")
            value_cell.fill=PatternFill("solid", fgColor=self.LIGHT); value_cell.font=Font(name="Segoe UI", size=14, bold=True)
            value_cell.alignment=Alignment(horizontal="center", vertical="center"); value_cell.number_format=fmt
        ws.merge_cells("A12:H12"); ws["A12"]="Executive Snapshot"; ws["A12"].fill=PatternFill("solid", fgColor=self.BLUE); ws["A12"].font=Font(bold=True,color=self.WHITE)
        snapshot = [
            ("Largest Holding", f"{s.largest_holding_symbol} ({s.largest_holding_pct:.2f}%)"),
            ("Average Position Value", s.average_position_value),
            ("Profitable Holdings", s.profitable_holdings), ("Loss-making Holdings", s.loss_making_holdings),
        ]
        for idx,(label,value) in enumerate(snapshot, start=13):
            ws.cell(idx,1,label).font=Font(bold=True); ws.cell(idx,2,value)
            if label == "Average Position Value": ws.cell(idx,2).number_format=self.CURRENCY
        for col in range(1,9): ws.column_dimensions[get_column_letter(col)].width=16
        self.configure_worksheet(ws, freeze_panes="A3", print_area="A1:H32")

    def _summary_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Summary")
        ws.append(["Metric", "Value"])
        s = self.summary; assert s is not None
        rows = [
            ("Total Investment", s.total_investment), ("Current Value", s.current_value), ("Profit / Loss", s.profit_loss),
            ("Return %", s.return_pct), ("Holdings Count", s.holdings_count), ("Sector Count", s.sector_count),
            ("Largest Holding Symbol", s.largest_holding_symbol), ("Largest Holding Value", s.largest_holding_value),
            ("Largest Holding %", s.largest_holding_pct), ("Average Position Value", s.average_position_value),
            ("Profitable Holdings", s.profitable_holdings), ("Loss-making Holdings", s.loss_making_holdings),
            ("Portfolio Health Score", s.portfolio_health_score),
        ]
        for row in rows: ws.append(row)
        for cell in ws[1]: cell.fill=PatternFill("solid", fgColor=self.BLUE); cell.font=Font(bold=True,color=self.WHITE)
        for row in (2,3,4,9,11): ws.cell(row,2).number_format=self.CURRENCY
        for row in (5,10): ws.cell(row,2).number_format=self.PERCENT
        ws.column_dimensions["A"].width=28; ws.column_dimensions["B"].width=22
        self.configure_worksheet(ws, freeze_panes="A2", print_area=f"A1:B{ws.max_row}")

    def _chart_data(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Chart Data")
        ws.append(["Symbol","Current Value","Profit","Allocation %","Sector"])
        for _, row in self.dataframe.iterrows():
            ws.append([row["Symbol"], float(row["Current Value"]), float(row["Profit"]), float(row["Allocation %"]), row["Sector"]])
        sector = self.dataframe.groupby("Sector", as_index=False)["Current Value"].sum().sort_values("Current Value", ascending=False)
        ws["G1"]="Sector"; ws["H1"]="Current Value"
        for idx,row in sector.iterrows(): ws.append([]) if False else None
        for offset,(_,row) in enumerate(sector.iterrows(), start=2): ws.cell(offset,7,row["Sector"]); ws.cell(offset,8,float(row["Current Value"]))

    def _charts(self, workbook) -> None:
        ws=workbook["Dashboard"]; data=workbook["Chart Data"]
        max_row=data.max_row
        bar=BarChart(); bar.type="col"; bar.style=10; bar.title="Top Holdings by Current Value"; bar.y_axis.title="Current Value"; bar.height=7; bar.width=13
        bar.add_data(Reference(data,min_col=2,min_row=1,max_row=min(max_row,11)), titles_from_data=True)
        bar.set_categories(Reference(data,min_col=1,min_row=2,max_row=min(max_row,11))); ws.add_chart(bar,"A18")
        sector_rows=max(1, len(self.dataframe["Sector"].unique()))
        pie=PieChart(); pie.title="Sector Allocation"; pie.height=7; pie.width=11
        pie.add_data(Reference(data,min_col=8,min_row=1,max_row=sector_rows+1), titles_from_data=True)
        pie.set_categories(Reference(data,min_col=7,min_row=2,max_row=sector_rows+1)); pie.dataLabels=DataLabelList(); pie.dataLabels.showPercent=True
        ws.add_chart(pie,"E18")
