"""
Finance Utility Suite
Client Holdings Excel Report

Author  : Shiva Kumar
Version : 1.36.0
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

import pandas as pd
from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import Alignment, Font
from openpyxl.worksheet.table import Table, TableStyleInfo

from desktop.reports.report_engine import ExcelReportEngine
from desktop.reports.chart_builder import (
    add_exposure_pie_chart,
    add_top_holdings_bar_chart,
)
from desktop.reports.analytics_builder import PortfolioAnalyticsBuilder
from desktop.reports.recommendation_engine import ExecutiveRecommendationEngine
from desktop.reports.excel_styles import (
    THEME,
    centered,
    label_font,
    normal_font,
    section_font,
    solid_fill,
    thin_border,
    title_font,
    value_font,
)


class ClientHoldingsReport(ExcelReportEngine):
    """Generate a professional client holdings workbook."""

    VERSION = "1.36.0"

    def __init__(
        self,
        account_id: str,
        holdings_df: pd.DataFrame,
        summary_data: dict[str, Any] | None = None,
    ) -> None:
        self.account_id = str(account_id).strip()
        self.holdings_df = holdings_df.copy()
        self.summary_data = dict(summary_data or {})

        super().__init__(
            report_title=f"Client Holdings Report - {self.account_id}",
            report_subject="Client concentration and holdings analysis",
            report_description=(
                "Professional client holdings report generated by "
                "Finance Utility Suite."
            ),
            report_keywords=(
                "client holdings, exposure, concentration, MTF, risk"
            ),
        )

    def build(
        self,
        writer: pd.ExcelWriter,
        export_time: datetime,
    ) -> None:
        """Build all client holdings report worksheets."""

        self._validate_report_data()
        self._create_executive_summary_sheet(writer, export_time)
        self.holdings_df.to_excel(writer, sheet_name="Holdings", index=False)
        self._format_holdings_sheet(writer)
        self._create_portfolio_analytics_sheet(writer)
        self._create_executive_intelligence_sheet(writer)
        self._create_chart_data_sheet(writer)

    def _validate_report_data(self) -> None:
        """Validate columns required by the client holdings report."""

        required = {
            "Symbol",
            "Exposure",
            "MarkToMarket",
            "MTF MARGIN",
            "Holding %",
        }
        missing = sorted(required.difference(self.holdings_df.columns))
        if missing:
            raise ValueError(
                "Missing required holdings columns: " + ", ".join(missing)
            )

    def _portfolio_metrics(self) -> dict[str, float]:
        holding_count = len(self.holdings_df)
        total_exposure = float(self.holdings_df["Exposure"].sum())
        total_mtm = float(self.holdings_df["MarkToMarket"].sum())
        total_margin = float(self.holdings_df["MTF MARGIN"].sum())

        weights = pd.to_numeric(
            self.holdings_df["Holding %"], errors="coerce"
        ).fillna(0.0)
        if weights.sum() <= 0 and total_exposure > 0:
            weights = (
                self.holdings_df["Exposure"]
                .clip(lower=0)
                .div(total_exposure)
                .mul(100)
            )

        largest = float(weights.max()) if not weights.empty else 0.0
        average = float(weights.mean()) if not weights.empty else 0.0
        top_three = float(weights.nlargest(3).sum()) if not weights.empty else 0.0
        average_exposure = total_exposure / holding_count if holding_count else 0.0
        diversification = self._calculate_diversification_score(weights)

        return {
            "holding_count": float(holding_count),
            "total_exposure": total_exposure,
            "total_mtm": total_mtm,
            "total_margin": total_margin,
            "largest_holding": largest,
            "average_holding": average,
            "top_three": top_three,
            "average_exposure": average_exposure,
            "diversification": diversification,
            "concentration": max(0.0, min(100.0, 100.0 - diversification)),
        }

    @staticmethod
    def _calculate_diversification_score(weights: pd.Series) -> float:
        clean = pd.to_numeric(weights, errors="coerce").fillna(0.0)
        clean = clean[clean > 0]
        count = len(clean)
        if count <= 1:
            return 0.0
        normalized = clean / clean.sum()
        hhi = float((normalized**2).sum())
        minimum_hhi = 1.0 / count
        denominator = 1.0 - minimum_hhi
        if denominator <= 0:
            return 0.0
        return max(0.0, min(100.0, ((1.0 - hhi) / denominator) * 100.0))

    def _create_executive_summary_sheet(
        self,
        writer: pd.ExcelWriter,
        export_time: datetime,
    ) -> None:
        workbook = writer.book
        worksheet = workbook.create_sheet("Executive Summary", 0)
        metrics = self._portfolio_metrics()

        risk_level = str(self.summary_data.get("Risk Level", "Unknown")).strip()
        risk_fill = {
            "Critical": THEME.red,
            "High": THEME.orange,
            "Medium": THEME.amber,
            "Low": THEME.green,
        }.get(risk_level, THEME.muted_text)

        border = thin_border()

        worksheet.merge_cells("A1:L1")
        worksheet["A1"] = "FINANCE UTILITY SUITE"
        worksheet["A1"].fill = solid_fill(THEME.dark_blue)
        worksheet["A1"].font = title_font(18)
        worksheet["A1"].alignment = centered()
        worksheet.row_dimensions[1].height = 30

        worksheet.merge_cells("A2:L2")
        worksheet["A2"] = "CLIENT HOLDINGS REPORT"
        worksheet["A2"].fill = solid_fill(THEME.medium_blue)
        worksheet["A2"].font = title_font(13)
        worksheet["A2"].alignment = centered()
        worksheet.row_dimensions[2].height = 24

        info_rows = [
            ("Account ID", self.account_id),
            ("Risk Level", risk_level),
            ("Generated On", export_time.strftime("%d-%m-%Y %I:%M:%S %p")),
            ("Report Version", self.VERSION),
        ]
        for row_number, (label, value) in enumerate(info_rows, start=4):
            label_cell = worksheet.cell(row=row_number, column=1, value=label)
            value_cell = worksheet.cell(row=row_number, column=2, value=value)
            label_cell.fill = solid_fill(THEME.light_blue)
            label_cell.font = Font(
                name="Segoe UI", size=10, bold=True, color=THEME.dark_text
            )
            value_cell.font = normal_font(10)
            label_cell.border = border
            value_cell.border = border
            label_cell.alignment = Alignment(vertical="center")
            value_cell.alignment = Alignment(vertical="center")

        worksheet["B5"].fill = solid_fill(risk_fill)
        worksheet["B5"].font = Font(
            name="Segoe UI", size=10, bold=True, color=THEME.white
        )
        worksheet["B5"].alignment = centered()

        worksheet.merge_cells("A9:F9")
        worksheet["A9"] = "EXECUTIVE KPI SUMMARY"
        worksheet["A9"].fill = solid_fill(THEME.dark_blue)
        worksheet["A9"].font = section_font()
        worksheet["A9"].alignment = Alignment(horizontal="left")

        cards = [
            ("Holdings", metrics["holding_count"], "0"),
            ("Total Exposure", metrics["total_exposure"], '₹#,##0.00'),
            ("Mark to Market", metrics["total_mtm"], '₹#,##0.00;[Red]-₹#,##0.00'),
            ("MTF Margin", metrics["total_margin"], '₹#,##0.00'),
            ("Largest Holding", metrics["largest_holding"] / 100, "0.00%"),
            ("Diversification Score", metrics["diversification"], "0.0"),
            ("Average Holding", metrics["average_holding"] / 100, "0.00%"),
            ("Top 3 Holdings", metrics["top_three"] / 100, "0.00%"),
            ("Concentration Score", metrics["concentration"], "0.0"),
            ("Average Exposure", metrics["average_exposure"], '₹#,##0.00'),
        ]
        positions = [
            (11, 1), (11, 3), (11, 5),
            (14, 1), (14, 3), (14, 5),
            (17, 1), (17, 3), (17, 5),
            (20, 1),
        ]

        for (label, value, number_format), (row, column) in zip(cards, positions):
            worksheet.merge_cells(
                start_row=row, start_column=column,
                end_row=row, end_column=column + 1,
            )
            worksheet.merge_cells(
                start_row=row + 1, start_column=column,
                end_row=row + 1, end_column=column + 1,
            )
            label_cell = worksheet.cell(row=row, column=column, value=label)
            value_cell = worksheet.cell(row=row + 1, column=column, value=value)
            value_cell.number_format = number_format
            label_cell.fill = solid_fill(THEME.pale_blue)
            value_cell.fill = solid_fill(THEME.white)
            label_cell.font = label_font()
            value_cell.font = value_font()
            label_cell.alignment = centered()
            value_cell.alignment = centered()
            for card_row in (row, row + 1):
                for card_column in (column, column + 1):
                    worksheet.cell(card_row, card_column).border = border
            worksheet.row_dimensions[row].height = 22
            worksheet.row_dimensions[row + 1].height = 30

        worksheet.merge_cells("A24:F24")
        worksheet["A24"] = (
            "This report is system generated from the current client "
            "holdings dataset."
        )
        worksheet["A24"].font = Font(
            name="Segoe UI", size=9, italic=True, color=THEME.muted_text
        )
        worksheet["A24"].alignment = centered()

        for letter, width in {
            "A": 20, "B": 18, "C": 20, "D": 18, "E": 20, "F": 18,
            "G": 3, "H": 16, "I": 16, "J": 16, "K": 16, "L": 16,
        }.items():
            worksheet.column_dimensions[letter].width = width

        self.configure_worksheet(
            worksheet,
            freeze_panes="A4",
            fit_to_height=1,
            print_area="A1:L36",
        )

    def _format_holdings_sheet(self, writer: pd.ExcelWriter) -> None:
        worksheet = writer.sheets["Holdings"]
        worksheet.freeze_panes = "A2"
        worksheet.sheet_view.showGridLines = False

        max_row = worksheet.max_row
        max_column = worksheet.max_column
        if max_row >= 1 and max_column >= 1:
            table = Table(displayName="ClientHoldingsTable", ref=worksheet.dimensions)
            table.tableStyleInfo = TableStyleInfo(
                name="TableStyleMedium2",
                showFirstColumn=False,
                showLastColumn=False,
                showRowStripes=True,
                showColumnStripes=False,
            )
            worksheet.add_table(table)

        self.autosize_columns(worksheet, self.holdings_df)

        header_map = {
            worksheet.cell(1, col).value: col for col in range(1, max_column + 1)
        }
        currency_columns = [
            "BUY VALUE", "NetValue", "Exposure", "MarkToMarket",
            "MTF VAR", "MTF MARGIN",
        ]
        for name in currency_columns:
            col = header_map.get(name)
            if col:
                for row in range(2, max_row + 1):
                    worksheet.cell(row, col).number_format = '₹#,##0.00;[Red]-₹#,##0.00'

        holding_col = header_map.get("Holding %")
        if holding_col:
            for row in range(2, max_row + 1):
                worksheet.cell(row, holding_col).number_format = '0.00"%"'

        mtm_col = header_map.get("MarkToMarket")
        if mtm_col and max_row >= 2:
            letter = worksheet.cell(1, mtm_col).column_letter
            worksheet.conditional_formatting.add(
                f"{letter}2:{letter}{max_row}",
                CellIsRule(
                    operator="lessThan",
                    formula=["0"],
                    fill=solid_fill("FEE2E2"),
                    font=Font(color=THEME.red),
                ),
            )
            worksheet.conditional_formatting.add(
                f"{letter}2:{letter}{max_row}",
                CellIsRule(
                    operator="greaterThanOrEqual",
                    formula=["0"],
                    fill=solid_fill("DCFCE7"),
                    font=Font(color=THEME.green),
                ),
            )

        self.configure_worksheet(
            worksheet,
            freeze_panes="A2",
            repeat_rows="1:1",
        )


    def _create_portfolio_analytics_sheet(self, writer: pd.ExcelWriter) -> None:
        """Create the Portfolio Analytics worksheet."""

        worksheet = writer.book.create_sheet("Portfolio Analytics")
        builder = PortfolioAnalyticsBuilder(
            account_id=self.account_id,
            holdings_df=self.holdings_df,
            metrics=self._portfolio_metrics(),
            summary_data=self.summary_data,
        )
        builder.build(worksheet)

    def _create_executive_intelligence_sheet(self, writer: pd.ExcelWriter) -> None:
        """Create the Executive Intelligence worksheet."""

        worksheet = writer.book.create_sheet("Executive Intelligence")
        engine = ExecutiveRecommendationEngine(
            account_id=self.account_id,
            holdings_df=self.holdings_df,
            metrics=self._portfolio_metrics(),
            summary_data=self.summary_data,
        )
        engine.build(worksheet)

    def _create_chart_data_sheet(self, writer: pd.ExcelWriter) -> None:
        workbook = writer.book
        summary_sheet = writer.sheets["Executive Summary"]
        data_sheet = workbook.create_sheet("Chart Data")

        positive = self.holdings_df[self.holdings_df["Exposure"] > 0].copy()
        positive = positive.sort_values("Exposure", ascending=False)
        top = positive.head(10).copy()
        remaining = float(positive.iloc[10:]["Exposure"].sum())
        if remaining > 0:
            top = pd.concat(
                [top, pd.DataFrame([{"Symbol": "Others", "Exposure": remaining}])],
                ignore_index=True,
            )

        data_sheet.cell(1, 1, "Symbol")
        data_sheet.cell(1, 2, "Exposure")
        for row_number, row in enumerate(top[["Symbol", "Exposure"]].itertuples(index=False), start=2):
            data_sheet.cell(row_number, 1, row.Symbol)
            data_sheet.cell(row_number, 2, float(row.Exposure))

        end_row = 1 + len(top)
        if end_row >= 2:
            add_exposure_pie_chart(summary_sheet, data_sheet, 2, end_row, "H4")
            bar_end = min(end_row, 11)
            add_top_holdings_bar_chart(summary_sheet, data_sheet, 2, bar_end, "H20")

        data_sheet.sheet_state = "hidden"
