"""
Finance Utility Suite
Portfolio Excel Report

Author   : Shiva Kumar
Version  : 1.40.0
Milestone: 04 - Portfolio Report Phase C
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Final

import pandas as pd
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.chart.label import DataLabelList
from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter, range_boundaries
from openpyxl.worksheet.table import Table, TableColumn, TableStyleInfo
from openpyxl.worksheet.worksheet import Worksheet

from desktop.reports.base_dashboard_report import BaseDashboardReport


class PortfolioReport(BaseDashboardReport):
    """Generate the final portfolio Excel report with dashboard and charts."""

    VERSION: Final[str] = "1.40.0"

    DARK_BLUE = "17365D"
    MEDIUM_BLUE = "2F75B5"
    LIGHT_BLUE = "D9EAF7"
    VERY_LIGHT_BLUE = "EEF5FB"
    WHITE = "FFFFFF"
    DARK_TEXT = "1F1F1F"
    GREEN = "008000"
    LIGHT_GREEN = "E2F0D9"
    RED = "C00000"
    LIGHT_RED = "FCE4D6"
    GOLD = "FFC000"
    GREY = "D9E1F2"

    CURRENCY_FORMAT = '₹#,##0.00;[Red]-₹#,##0.00'
    PERCENT_FORMAT = '0.00"%"'
    NUMBER_FORMAT = '#,##0.00'

    COLUMN_ALIASES: Final[dict[str, tuple[str, ...]]] = {
        "Symbol": ("Symbol", "SYMBOL", "symbol", "Stock", "Scrip"),
        "Quantity": ("Quantity", "QTY", "Qty", "quantity", "NetQty"),
        "Average Price": (
            "Average Price", "Avg Price", "AVG PRICE",
            "Buy Price", "Purchase Price",
        ),
        "Current Price": (
            "Current Price", "LTP", "Market Price", "Last Price",
        ),
        "Investment": (
            "Investment", "Invested Value", "Investment Value",
            "Cost Value", "Buy Value",
        ),
        "Current Value": (
            "Current Value", "Market Value", "Present Value",
        ),
        "Profit": (
            "Profit", "Profit / Loss", "P/L", "PnL", "Unrealized P/L",
        ),
        "Return %": (
            "Return %", "Return Percent", "P/L %", "Profit %",
        ),
        "Sector": ("Sector", "Industry", "Category"),
    }

    REQUIRED_COLUMNS: Final[tuple[str, ...]] = (
        "Symbol",
        "Quantity",
        "Average Price",
        "Current Price",
    )

    def __init__(
        self,
        dataframe: pd.DataFrame,
        summary_data: dict[str, Any] | None = None,
        *,
        portfolio_name: str = "Portfolio",
    ) -> None:
        self.portfolio_name = str(portfolio_name).strip() or "Portfolio"
        self.source_dataframe = dataframe.copy()
        self.summary_data = dict(summary_data or {})
        self.dataframe = pd.DataFrame()

        super().__init__(
            report_title=f"{self.portfolio_name} Report",
            report_subject="Portfolio holdings and performance analysis",
            report_description=(
                "Professional portfolio report generated by "
                "Finance Utility Suite."
            ),
            report_keywords=(
                "portfolio, holdings, investment, market value, "
                "profit loss, returns, allocation"
            ),
        )

    # ------------------------------------------------------------------
    # Workbook build
    # ------------------------------------------------------------------

    def build(self, writer: pd.ExcelWriter, export_time: datetime) -> None:
        """Build the complete portfolio workbook."""

        self.dataframe = self._prepare_dataframe(self.source_dataframe)
        self._validate_dataframe()

        self._create_dashboard_sheet(writer, export_time)
        self._create_holdings_sheet(writer)
        self._create_performance_sheet(writer)
        self._create_allocation_sheet(writer)
        self._create_chart_data_sheet(writer)
        self._add_dashboard_charts(writer.book)

        chart_data = writer.book["Chart Data"]
        chart_data.sheet_state = "hidden"

        writer.book.active = writer.book.sheetnames.index("Dashboard")

    # ------------------------------------------------------------------
    # Data preparation
    # ------------------------------------------------------------------

    def _prepare_dataframe(self, dataframe: pd.DataFrame) -> pd.DataFrame:
        if dataframe is None or dataframe.empty:
            raise ValueError("Portfolio data is empty.")

        frame = dataframe.copy()
        rename_map: dict[str, str] = {}

        for canonical, aliases in self.COLUMN_ALIASES.items():
            if canonical in frame.columns:
                continue
            match = next((name for name in aliases if name in frame.columns), None)
            if match:
                rename_map[match] = canonical

        if rename_map:
            frame = frame.rename(columns=rename_map)

        missing = [
            name for name in self.REQUIRED_COLUMNS
            if name not in frame.columns
        ]
        if missing:
            raise ValueError(
                "Missing required portfolio columns: " + ", ".join(missing)
            )

        numeric_columns = (
            "Quantity", "Average Price", "Current Price",
            "Investment", "Current Value", "Profit", "Return %",
        )
        for column in numeric_columns:
            if column in frame.columns:
                frame[column] = pd.to_numeric(
                    frame[column], errors="coerce"
                ).fillna(0.0)

        frame["Symbol"] = (
            frame["Symbol"].fillna("").astype(str).str.strip().str.upper()
        )
        frame = frame[frame["Symbol"] != ""].copy()

        if frame.empty:
            raise ValueError("Portfolio contains no valid symbols.")

        if "Investment" not in frame.columns:
            frame["Investment"] = (
                frame["Quantity"] * frame["Average Price"]
            )

        if "Current Value" not in frame.columns:
            frame["Current Value"] = (
                frame["Quantity"] * frame["Current Price"]
            )

        if "Profit" not in frame.columns:
            frame["Profit"] = (
                frame["Current Value"] - frame["Investment"]
            )

        if "Return %" not in frame.columns:
            safe_investment = frame["Investment"].where(
                frame["Investment"] != 0
            )
            frame["Return %"] = (
                frame["Profit"]
                .div(safe_investment)
                .mul(100)
                .replace([float("inf"), float("-inf")], 0)
                .fillna(0)
            )

        if "Sector" not in frame.columns:
            frame["Sector"] = "Unclassified"
        else:
            frame["Sector"] = (
                frame["Sector"]
                .fillna("Unclassified")
                .astype(str)
                .str.strip()
                .replace("", "Unclassified")
            )

        # Consolidate duplicate symbols so charts and rankings remain accurate.
        aggregation: dict[str, str] = {
            "Sector": "first",
            "Quantity": "sum",
            "Investment": "sum",
            "Current Value": "sum",
            "Profit": "sum",
        }
        grouped = frame.groupby("Symbol", as_index=False).agg(aggregation)

        grouped["Average Price"] = grouped["Investment"].div(
            grouped["Quantity"].where(grouped["Quantity"] != 0)
        ).fillna(0)

        grouped["Current Price"] = grouped["Current Value"].div(
            grouped["Quantity"].where(grouped["Quantity"] != 0)
        ).fillna(0)

        grouped["Return %"] = grouped["Profit"].div(
            grouped["Investment"].where(grouped["Investment"] != 0)
        ).mul(100).fillna(0)

        order = [
            "Symbol", "Sector", "Quantity", "Average Price",
            "Current Price", "Investment", "Current Value",
            "Profit", "Return %",
        ]
        return grouped[order].sort_values(
            "Current Value", ascending=False
        ).reset_index(drop=True)

    def _validate_dataframe(self) -> None:
        if self.dataframe.empty:
            raise ValueError("Portfolio contains no valid holdings.")

    # ------------------------------------------------------------------
    # Metrics
    # ------------------------------------------------------------------

    def _metrics(self) -> dict[str, float]:
        investment = float(self.dataframe["Investment"].sum())
        current_value = float(self.dataframe["Current Value"].sum())
        profit = float(self.dataframe["Profit"].sum())
        return_percent = profit / investment * 100 if investment else 0.0

        gainers = int((self.dataframe["Profit"] > 0).sum())
        losers = int((self.dataframe["Profit"] < 0).sum())

        largest_holding = (
            float(self.dataframe["Current Value"].max()) / current_value * 100
            if current_value else 0.0
        )

        positive_ratio = (
            gainers / len(self.dataframe) * 100
            if len(self.dataframe) else 0.0
        )

        concentration_penalty = max(largest_holding - 20, 0) * 1.2
        return_bonus = max(min(return_percent, 25), -25) * 1.4
        breadth_bonus = positive_ratio * 0.25

        health_score = max(
            0.0,
            min(100.0, 50 + return_bonus + breadth_bonus - concentration_penalty),
        )

        return {
            "holdings": float(len(self.dataframe)),
            "investment": investment,
            "current_value": current_value,
            "profit": profit,
            "return_percent": return_percent,
            "gainers": float(gainers),
            "losers": float(losers),
            "largest_holding": largest_holding,
            "health_score": health_score,
        }

    # ------------------------------------------------------------------
    # Dashboard
    # ------------------------------------------------------------------

    def _create_dashboard_sheet(
        self,
        writer: pd.ExcelWriter,
        export_time: datetime,
    ) -> None:
        ws = writer.book.create_sheet("Dashboard", 0)
        ws.sheet_view.showGridLines = False
        ws.freeze_panes = "A9"

        for column in range(1, 17):
            ws.column_dimensions[get_column_letter(column)].width = 13

        ws.merge_cells("A1:P1")
        ws["A1"] = "FINANCE UTILITY SUITE"
        self._style_title(ws["A1"], 20, self.DARK_BLUE)
        ws.row_dimensions[1].height = 34

        ws.merge_cells("A2:P2")
        ws["A2"] = f"{self.portfolio_name.upper()} DASHBOARD"
        self._style_title(ws["A2"], 14, self.MEDIUM_BLUE)
        ws.row_dimensions[2].height = 26

        ws.merge_cells("A3:H3")
        ws["A3"] = f"Generated: {export_time:%d-%m-%Y %I:%M %p}"
        ws["A3"].font = Font(name="Segoe UI", size=9, italic=True)
        ws["A3"].alignment = Alignment(horizontal="left")

        ws.merge_cells("I3:P3")
        ws["I3"] = f"Report Version: {self.VERSION}"
        ws["I3"].font = Font(name="Segoe UI", size=9, italic=True)
        ws["I3"].alignment = Alignment(horizontal="right")

        metrics = self._metrics()
        cards = [
            ("TOTAL INVESTMENT", metrics["investment"], self.CURRENCY_FORMAT),
            ("CURRENT VALUE", metrics["current_value"], self.CURRENCY_FORMAT),
            ("PROFIT / LOSS", metrics["profit"], self.CURRENCY_FORMAT),
            ("RETURN", metrics["return_percent"], self.PERCENT_FORMAT),
            ("HOLDINGS", metrics["holdings"], "0"),
            ("GAINERS", metrics["gainers"], "0"),
            ("LOSERS", metrics["losers"], "0"),
            ("HEALTH SCORE", metrics["health_score"], '0.00"/100"'),
        ]

        positions = [
            ("A5:D7"), ("E5:H7"), ("I5:L7"), ("M5:P7"),
            ("A9:D11"), ("E9:H11"), ("I9:L11"), ("M9:P11"),
        ]

        for (label, value, number_format), cell_range in zip(cards, positions):
            self._write_kpi_card(ws, cell_range, label, value, number_format)

        ws["A13"] = "Portfolio Allocation"
        ws["I13"] = "Profit / Loss by Stock"
        ws["A30"] = "Top Holdings"
        ws["I30"] = "Sector Allocation"

        for cell in ("A13", "I13", "A30", "I30"):
            ws[cell].font = Font(
                name="Segoe UI", size=11, bold=True, color=self.DARK_BLUE
            )

        ws.oddHeader.center.text = "Finance Utility Suite - Portfolio Dashboard"
        ws.oddFooter.left.text = f"{self.portfolio_name} Report"
        ws.oddFooter.center.text = "Confidential"
        ws.oddFooter.right.text = "Page &P of &N"

        ws.page_setup.orientation = "landscape"
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToWidth = 1
        ws.page_setup.fitToHeight = 1
        ws.sheet_properties.pageSetUpPr.fitToPage = True
        ws.print_area = "A1:P47"

    def _write_kpi_card(
        self,
        ws: Worksheet,
        cell_range: str,
        label: str,
        value: float,
        number_format: str,
    ) -> None:
        start, end = cell_range.split(":")
        start_col = ws[start].column
        start_row = ws[start].row
        end_col = ws[end].column
        end_row = ws[end].row

        ws.merge_cells(
            start_row=start_row,
            start_column=start_col,
            end_row=end_row,
            end_column=end_col,
        )

        cell = ws.cell(start_row, start_col)
        cell.value = value
        cell.number_format = number_format
        cell.font = Font(
            name="Segoe UI", size=16, bold=True, color=self.DARK_TEXT
        )
        cell.alignment = Alignment(
            horizontal="center",
            vertical="center",
            wrap_text=True,
        )
        cell.fill = PatternFill("solid", fgColor=self.VERY_LIGHT_BLUE)
        cell.border = self._border()

        label_cell = ws.cell(start_row, start_col)
        label_cell.comment = None

        # Place a compact label above the merged card.
        ws.cell(start_row - 1, start_col, label)
        ws.merge_cells(
            start_row=start_row - 1,
            start_column=start_col,
            end_row=start_row - 1,
            end_column=end_col,
        )
        header = ws.cell(start_row - 1, start_col)
        header.fill = PatternFill("solid", fgColor=self.MEDIUM_BLUE)
        header.font = Font(
            name="Segoe UI", size=9, bold=True, color=self.WHITE
        )
        header.alignment = Alignment(horizontal="center", vertical="center")
        header.border = self._border()

        if label == "PROFIT / LOSS":
            cell.fill = PatternFill(
                "solid",
                fgColor=self.LIGHT_GREEN if value >= 0 else self.LIGHT_RED,
            )

    # ------------------------------------------------------------------
    # Holdings
    # ------------------------------------------------------------------

    def _create_holdings_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Holdings")
        ws.sheet_view.showGridLines = False

        self._write_sheet_heading(
            ws,
            title="PORTFOLIO HOLDINGS",
            subtitle="Detailed position-level portfolio statement",
            end_column=9,
        )

        start_row = 5
        self._write_dataframe(ws, self.dataframe, start_row, 1)
        end_row = start_row + len(self.dataframe)

        self._add_table(
            ws,
            f"A{start_row}:I{end_row}",
            "PortfolioHoldings",
        )
        self._apply_holdings_formats(ws, start_row + 1, end_row)

        ws.freeze_panes = f"A{start_row + 1}"
        ws.print_title_rows = f"{start_row}:{start_row}"
        self._set_page_layout(ws, f"A1:I{end_row}")
        self._autosize(ws, 28)

    # ------------------------------------------------------------------
    # Performance
    # ------------------------------------------------------------------

    def _create_performance_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Performance")
        ws.sheet_view.showGridLines = False

        performance = self.dataframe[
            ["Symbol", "Investment", "Current Value", "Profit", "Return %"]
        ].sort_values("Return %", ascending=False)

        self._write_sheet_heading(
            ws,
            title="PORTFOLIO PERFORMANCE",
            subtitle="Ranked by return percentage",
            end_column=5,
        )

        start_row = 5
        self._write_dataframe(ws, performance, start_row, 1)
        end_row = start_row + len(performance)

        self._add_table(
            ws,
            f"A{start_row}:E{end_row}",
            "PortfolioPerformance",
        )

        for row in range(start_row + 1, end_row + 1):
            for col in (2, 3, 4):
                ws.cell(row, col).number_format = self.CURRENCY_FORMAT
            ws.cell(row, 5).number_format = self.PERCENT_FORMAT

        self._add_profit_loss_rules(
            ws,
            f"D{start_row + 1}:D{end_row}",
        )
        self._add_profit_loss_rules(
            ws,
            f"E{start_row + 1}:E{end_row}",
        )

        ws.freeze_panes = f"A{start_row + 1}"
        ws.print_title_rows = f"{start_row}:{start_row}"
        self._set_page_layout(ws, f"A1:E{end_row}")
        self._autosize(ws, 28)

    # ------------------------------------------------------------------
    # Allocation
    # ------------------------------------------------------------------

    def _create_allocation_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Allocation")
        ws.sheet_view.showGridLines = False

        total_value = float(self.dataframe["Current Value"].sum())

        sector = (
            self.dataframe.groupby("Sector", as_index=False)["Current Value"]
            .sum()
            .sort_values("Current Value", ascending=False)
        )
        sector["Allocation %"] = (
            sector["Current Value"] / total_value * 100
            if total_value else 0.0
        )

        holdings = self.dataframe[
            ["Symbol", "Current Value"]
        ].sort_values("Current Value", ascending=False).copy()
        holdings["Allocation %"] = (
            holdings["Current Value"] / total_value * 100
            if total_value else 0.0
        )

        self._write_sheet_heading(
            ws,
            title="PORTFOLIO ALLOCATION",
            subtitle="Sector and holding concentration",
            end_column=7,
        )

        ws["A5"] = "SECTOR ALLOCATION"
        ws["E5"] = "HOLDING ALLOCATION"
        for cell in ("A5", "E5"):
            ws[cell].font = Font(
                name="Segoe UI", size=11, bold=True, color=self.DARK_BLUE
            )

        self._write_dataframe(ws, sector, 7, 1)
        sector_end = 7 + len(sector)
        self._add_table(
            ws,
            f"A7:C{sector_end}",
            "SectorAllocation",
        )

        self._write_dataframe(ws, holdings, 7, 5)
        holding_end = 7 + len(holdings)
        self._add_table(
            ws,
            f"E7:G{holding_end}",
            "HoldingAllocation",
        )

        for row in range(8, sector_end + 1):
            ws.cell(row, 2).number_format = self.CURRENCY_FORMAT
            ws.cell(row, 3).number_format = self.PERCENT_FORMAT

        for row in range(8, holding_end + 1):
            ws.cell(row, 6).number_format = self.CURRENCY_FORMAT
            ws.cell(row, 7).number_format = self.PERCENT_FORMAT

        ws.freeze_panes = "A8"
        self._set_page_layout(
            ws,
            f"A1:G{max(sector_end, holding_end)}",
        )
        self._autosize(ws, 28)

    # ------------------------------------------------------------------
    # Hidden chart data and charts
    # ------------------------------------------------------------------

    def _create_chart_data_sheet(self, writer: pd.ExcelWriter) -> None:
        ws = writer.book.create_sheet("Chart Data")
        ws.sheet_view.showGridLines = False

        total_value = float(self.dataframe["Current Value"].sum())

        holding_allocation = self.dataframe[
            ["Symbol", "Current Value"]
        ].sort_values("Current Value", ascending=False).copy()
        holding_allocation["Allocation %"] = (
            holding_allocation["Current Value"] / total_value * 100
            if total_value else 0.0
        )

        top_holdings = holding_allocation.head(10).copy()

        profit_loss = self.dataframe[
            ["Symbol", "Profit"]
        ].sort_values("Profit", ascending=False).head(15)

        sector = (
            self.dataframe.groupby("Sector", as_index=False)["Current Value"]
            .sum()
            .sort_values("Current Value", ascending=False)
        )

        self._write_dataframe(ws, holding_allocation, 1, 1)
        self._write_dataframe(ws, profit_loss, 1, 5)
        self._write_dataframe(ws, top_holdings, 1, 8)
        self._write_dataframe(ws, sector, 1, 12)

    def _add_dashboard_charts(self, workbook) -> None:
        dashboard = workbook["Dashboard"]
        data = workbook["Chart Data"]

        holdings_count = len(self.dataframe)
        profit_count = min(len(self.dataframe), 15)
        top_count = min(len(self.dataframe), 10)
        sector_count = int(self.dataframe["Sector"].nunique())

        portfolio_chart = PieChart()
        portfolio_chart.title = "Portfolio Allocation"
        portfolio_chart.height = 8.0
        portfolio_chart.width = 11.5
        portfolio_chart.legend.position = "r"
        portfolio_chart.varyColors = True
        portfolio_chart.add_data(
            Reference(data, min_col=2, min_row=1, max_row=holdings_count + 1),
            titles_from_data=True,
        )
        portfolio_chart.set_categories(
            Reference(data, min_col=1, min_row=2, max_row=holdings_count + 1)
        )
        portfolio_chart.dataLabels = DataLabelList()
        portfolio_chart.dataLabels.showPercent = True
        dashboard.add_chart(portfolio_chart, "A14")

        profit_chart = BarChart()
        profit_chart.type = "bar"
        profit_chart.style = 10
        profit_chart.title = "Profit / Loss by Stock"
        profit_chart.y_axis.title = "Symbol"
        profit_chart.x_axis.title = "Profit / Loss"
        profit_chart.height = 8.0
        profit_chart.width = 11.5
        profit_chart.legend = None
        profit_chart.add_data(
            Reference(data, min_col=6, min_row=1, max_row=profit_count + 1),
            titles_from_data=True,
        )
        profit_chart.set_categories(
            Reference(data, min_col=5, min_row=2, max_row=profit_count + 1)
        )
        dashboard.add_chart(profit_chart, "I14")

        top_chart = BarChart()
        top_chart.type = "col"
        top_chart.style = 11
        top_chart.title = "Top 10 Holdings"
        top_chart.y_axis.title = "Current Value"
        top_chart.x_axis.title = "Symbol"
        top_chart.height = 8.0
        top_chart.width = 11.5
        top_chart.legend = None
        top_chart.add_data(
            Reference(data, min_col=9, min_row=1, max_row=top_count + 1),
            titles_from_data=True,
        )
        top_chart.set_categories(
            Reference(data, min_col=8, min_row=2, max_row=top_count + 1)
        )
        dashboard.add_chart(top_chart, "A31")

        sector_chart = PieChart()
        sector_chart.title = "Sector Allocation"
        sector_chart.height = 8.0
        sector_chart.width = 11.5
        sector_chart.legend.position = "r"
        sector_chart.varyColors = True
        sector_chart.add_data(
            Reference(data, min_col=13, min_row=1, max_row=sector_count + 1),
            titles_from_data=True,
        )
        sector_chart.set_categories(
            Reference(data, min_col=12, min_row=2, max_row=sector_count + 1)
        )
        sector_chart.dataLabels = DataLabelList()
        sector_chart.dataLabels.showPercent = True
        dashboard.add_chart(sector_chart, "I31")

    # ------------------------------------------------------------------
    # Styling helpers
    # ------------------------------------------------------------------

    def _write_sheet_heading(
        self,
        ws: Worksheet,
        *,
        title: str,
        subtitle: str,
        end_column: int,
    ) -> None:
        ws.merge_cells(
            start_row=1,
            start_column=1,
            end_row=1,
            end_column=end_column,
        )
        ws["A1"] = title
        self._style_title(ws["A1"], 17, self.DARK_BLUE)
        ws.row_dimensions[1].height = 30

        ws.merge_cells(
            start_row=2,
            start_column=1,
            end_row=2,
            end_column=end_column,
        )
        ws["A2"] = subtitle
        ws["A2"].font = Font(
            name="Segoe UI", size=10, italic=True, color=self.DARK_TEXT
        )
        ws["A2"].alignment = Alignment(horizontal="center")

    def _write_dataframe(
        self,
        ws: Worksheet,
        dataframe: pd.DataFrame,
        start_row: int,
        start_column: int,
    ) -> None:
        for offset, column in enumerate(dataframe.columns):
            cell = ws.cell(start_row, start_column + offset, column)
            cell.fill = PatternFill("solid", fgColor=self.MEDIUM_BLUE)
            cell.font = Font(
                name="Segoe UI", size=10, bold=True, color=self.WHITE
            )
            cell.alignment = Alignment(
                horizontal="center", vertical="center"
            )
            cell.border = self._border()

        for row_offset, row in enumerate(
            dataframe.itertuples(index=False, name=None),
            start=1,
        ):
            for col_offset, value in enumerate(row):
                cell = ws.cell(
                    start_row + row_offset,
                    start_column + col_offset,
                    value,
                )
                cell.font = Font(name="Segoe UI", size=10)
                cell.alignment = Alignment(vertical="center")
                cell.border = self._border()

    def _apply_holdings_formats(
        self,
        ws: Worksheet,
        start_row: int,
        end_row: int,
    ) -> None:
        for row in range(start_row, end_row + 1):
            ws.cell(row, 3).number_format = self.NUMBER_FORMAT
            for col in (4, 5, 6, 7, 8):
                ws.cell(row, col).number_format = self.CURRENCY_FORMAT
            ws.cell(row, 9).number_format = self.PERCENT_FORMAT

        self._add_profit_loss_rules(ws, f"H{start_row}:H{end_row}")
        self._add_profit_loss_rules(ws, f"I{start_row}:I{end_row}")

    def _add_table(
        self,
        ws: Worksheet,
        reference: str,
        name: str,
    ) -> None:
        """Add a structurally valid Excel table.

        openpyxl initialises table-column IDs from the worksheet's absolute
        column numbers. For a table beginning in column E, that can produce
        IDs 5, 6, 7 even though the table contains only three columns.
        Desktop Excel may repair or remove that table definition.

        Build the table columns explicitly with sequential IDs starting at 1.
        """
        min_col, min_row, max_col, max_row = range_boundaries(reference)

        if max_row <= min_row:
            raise ValueError(
                f"Excel table '{name}' requires a header row and at least one data row."
            )
        if max_col < min_col:
            raise ValueError(f"Invalid Excel table range: {reference}")

        existing_names = {
            table.displayName
            for worksheet in ws.parent.worksheets
            for table in worksheet.tables.values()
        }
        if name in existing_names:
            raise ValueError(f"Duplicate Excel table name: {name}")

        headers: list[str] = []
        for column in range(min_col, max_col + 1):
            value = ws.cell(min_row, column).value
            header = "" if value is None else str(value).strip()
            if not header:
                raise ValueError(
                    f"Excel table '{name}' contains a blank header "
                    f"at row {min_row}, column {column}."
                )
            headers.append(header)

        if len(headers) != len(set(headers)):
            raise ValueError(
                f"Excel table '{name}' contains duplicate column headers."
            )

        table = Table(displayName=name, ref=reference)
        table.tableColumns = [
            TableColumn(id=index, name=header)
            for index, header in enumerate(headers, start=1)
        ]
        table.tableStyleInfo = TableStyleInfo(
            name="TableStyleMedium2",
            showFirstColumn=False,
            showLastColumn=False,
            showRowStripes=True,
            showColumnStripes=False,
        )
        ws.add_table(table)

    def _add_profit_loss_rules(
        self,
        ws: Worksheet,
        cell_range: str,
    ) -> None:
        ws.conditional_formatting.add(
            cell_range,
            CellIsRule(
                operator="greaterThanOrEqual",
                formula=["0"],
                fill=PatternFill("solid", fgColor=self.LIGHT_GREEN),
                font=Font(color=self.GREEN),
            ),
        )
        ws.conditional_formatting.add(
            cell_range,
            CellIsRule(
                operator="lessThan",
                formula=["0"],
                fill=PatternFill("solid", fgColor=self.LIGHT_RED),
                font=Font(color=self.RED),
            ),
        )

    def _set_page_layout(self, ws: Worksheet, print_area: str) -> None:
        ws.oddHeader.center.text = "Finance Utility Suite"
        ws.oddFooter.left.text = f"{self.portfolio_name} Report"
        ws.oddFooter.center.text = "Confidential"
        ws.oddFooter.right.text = "Page &P of &N"
        ws.page_setup.orientation = "landscape"
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToWidth = 1
        ws.page_setup.fitToHeight = 0
        ws.sheet_properties.pageSetUpPr.fitToPage = True
        ws.print_area = print_area

    @classmethod
    def _style_title(
        cls,
        cell,
        size: int,
        fill_color: str,
    ) -> None:
        cell.fill = PatternFill("solid", fgColor=fill_color)
        cell.font = Font(
            name="Segoe UI", size=size, bold=True, color=cls.WHITE
        )
        cell.alignment = Alignment(
            horizontal="center", vertical="center"
        )
        cell.border = cls._border()

    @classmethod
    def _border(cls) -> Border:
        side = Side(style="thin", color="B7C9E2")
        return Border(left=side, right=side, top=side, bottom=side)

    @staticmethod
    def _autosize(ws: Worksheet, maximum_width: int = 30) -> None:
        for column_cells in ws.columns:
            column_letter = get_column_letter(column_cells[0].column)
            width = 0
            for cell in column_cells:
                if cell.value is None:
                    continue
                width = max(width, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = min(
                max(width + 2, 10),
                maximum_width,
            )
